version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  smtp:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    ports:
      - "1025:25"   # SMTP service (use port 25 for sending emails)
      - "5001:80"   # Web UI for smtp4dev (accessible at http://localhost:5000)
    environment:
      - SMTP_DOMAIN=localhost
      - SMTP_PORT=25
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  web:
    build: .
    container_name: flask_app
    environment:
      - FLASK_APP=run.py            # Ensure this points to the correct entry file
      - FLASK_ENV=development       # Enable development mode for Flask
      - DATABASE_URL=mysql://user:userpassword@db/flaskdb  # Database connection URL
    ports:
      - "5000:5000"
    depends_on:
      - db
      - smtp
    volumes:
      - .:/app                      # Mount the current directory to /app in the container
    command: watchmedo auto-restart --patterns="*.py;*.html;*.css;.env" --recursive -- flask run --host=0.0.0.0

volumes:
  mysql-data:                        # Volume for persisting MySQL data

